security:
    enable_authenticator_manager: true
    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'
        App\Entity\Customer:
            algorithm: auto
        App\Entity\Fixer:
            algorithm: auto
        App\Entity\Admin:
            algorithm: auto

    providers:
        customer_provider:
            entity:
                class: App\Entity\Customer
                property: email
        fixer_provider:
            entity:
                class: App\Entity\Fixer
                property: email
        admin_provider:
            entity:
                class: App\Entity\Admin
                property: email

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        fixer_context:
            pattern: ^/fixer/
            provider: fixer_provider
            custom_authenticator: App\Security\FixerAuthenticator
            logout:
                path: fixer_logout
                target: homepage

        admin_context:
            pattern: ^/admin/
            provider: admin_provider
            custom_authenticator: App\Security\AdminAuthenticator
            logout:
                path: admin_logout
                target: homepage

        customer_context:
            pattern: ^/
            provider: customer_provider
            custom_authenticator: App\Security\CustomerAuthenticator
            logout:
                path: customer_logout
                target: homepage

    access_control:
        - { path: /(login|register), roles: PUBLIC_ACCESS }
        - { path: ^/(admin|fixer)/, roles: ROLE_USER }
        - { path: ^/request, roles: ROLE_USER }
